name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    runs-on: arc-runner-set
    container:
      image: golang:1.23.0-bookworm
    steps:
    - name: Check Go Version
      run: go version
